stustapay/stustapay

etc/bon.conf, pyproject.toml, stustapay/bon/__main__.py, stustapay/bon/config.py, stustapay/bon/generator.py, stustapay/bon/pdflatex.py, stustapay/bon/tex/bon.tex, stustapay/core/schema/db/0000-base.sql, stustapay/tests/test_bongenerator.py
=> bon: provide all custom bon data from the database and add output folder configuration option

app/app/src/main/java/de/stustanet/stustapay/ui/deposit/DepositView.kt, app/app/src/main/java/de/stustanet/stustapay/ui/deposit/DepositViewModel.kt, app/app/src/main/java/de/stustanet/stustapay/ui/order/OrderView.kt, app/app/src/main/java/de/stustanet/stustapay/ui/order/OrderViewModel.kt
This PR adds haptic feedback, adjusts the order and deposit views for better usability in a festival environment and refactors some of the UI code.
Special thanks to @mic-e and @jn
=> app: improve order and deposit views

.github/workflows/ci.yaml, app/app/src/main/java/de/stustanet/stustapay/ui/chipscan/ChipScanView.kt
=> ci: add build for app

flake.lock, flake.nix
This PR adds configuration files that make developing on Nix / NixOS more convenient
=> core: add nix build files

README.md, doc/administration.md, doc/core.md, doc/customerportal.md, doc/install.md, doc/userportal.md, doc/web.md, stustapay/core/schema/customer.py.rej, web/apps/administration/src/app/ErrorPage.tsx
- added customer portal to the documentation
- fixed typos
- clarified config file naming
=> docu: added customer portal, general improvements

etc/server.conf, pyproject.toml, stustapay/core/__main__.py, stustapay/core/admin.py, stustapay/core/config.py, stustapay/core/customer_bank_export.py, stustapay/core/schema/db/0000-base.sql, stustapay/core/service/customer.py, stustapay/tests/common.py
- SEPA export
- own customer export CLI for SEPA and CSV
=> Customer Portal: Added SEPA Export for Customer Data

stustapay/core/customer_bank_export.py, stustapay/core/service/customer.py
- Added support for batch export to counter act bank errors which state that only n many transactions can be triggered with one sepa file
- Generalized export function interface
=> cp export: Batch export support

stustapay/core/schema/db/0000-base.sql, stustapay/tests/common.py, stustapay/tests/test_customer_service.py, stustapay/tse/diebold_nixdorf_usb/handler.py, stustapay/tse/diebold_nixdorf_usb/simulator.py
- tests for customer portal
- fixed tse import formats
- fixed default value in sql schema for `order_value`
- added database json return in tests for dataclass parsing
=> Tests for Customer Portal Service

stustapay/core/service/customer.py, stustapay/tests/common.py, stustapay/tests/test_customer_service.py
- test cleanup
- added further test for customer services
- added tests for customer bank export cli
- fixed discovered bugs
=> cp: add tests and some cleanup

stustapay/core/config.py, stustapay/core/database.py
to pin the accepted server cert
=> core: allow passing ssl root cert to db connection

app/app/src/main/java/de/stustanet/stustapay/MainActivity.kt, app/app/src/main/java/de/stustanet/stustapay/nfc/NfcHandler.kt, app/app/src/main/java/de/stustanet/stustapay/ui/root/StartpageView.kt, app/app/src/main/java/de/stustanet/stustapay/ui/root/StartpageViewModel.kt, app/app/src/main/res/values-de/strings.xml, app/app/src/main/res/values/strings.xml, stustapay/core/service/till/register.py
make everything ok
http://make-everything-ok.com/
=> app: make everything ok

app/app/src/main/java/de/stustanet/stustapay/ui/account/AccountScan.kt, app/app/src/main/java/de/stustanet/stustapay/ui/common/FailureIcon.kt, app/app/src/main/java/de/stustanet/stustapay/ui/common/SuccessIcon.kt, app/app/src/main/java/de/stustanet/stustapay/ui/common/pay/ErrorScreen.kt, app/app/src/main/java/de/stustanet/stustapay/ui/reward/RewardView.kt, app/app/src/main/java/de/stustanet/stustapay/ui/reward/RewardViewModel.kt, app/app/src/main/java/de/stustanet/stustapay/ui/sale/SaleError.kt, app/app/src/main/java/de/stustanet/stustapay/ui/sale/SaleSuccess.kt, app/app/src/main/res/values-de/strings.xml, app/app/src/main/res/values/strings.xml
=> Better reward feedback

app/app/src/main/java/de/stustanet/stustapay/ui/common/TagTextField.kt, app/app/src/main/java/de/stustanet/stustapay/ui/payinout/topup/TopUpSelection.kt, app/app/src/main/java/de/stustanet/stustapay/ui/ticket/TicketDraft.kt, app/app/src/main/java/de/stustanet/stustapay/ui/ticket/TicketViewModel.kt, app/app/src/main/res/values-de/strings.xml, app/app/src/main/res/values/strings.xml
ticket sales have a fixed order id -> we need a failure counter for sumup transaction ids.
=> Unique ec ids for ticket sale

app/app/src/main/java/de/stustanet/stustapay/ui/root/StartpageView.kt, app/app/src/main/res/values-de/strings.xml, app/app/src/main/res/values/strings.xml
always show apprestart, hide login when config's missing.
=> app startpage buttons

web/apps/administration/src/app/routes/tills/TillDetail.tsx
so it can be read in dark mode
=> fix(administration): registration qr code padding

app/app/.gitignore, app/app/src/main/java/de/stustanet/stustapay/ui/user/UserDisplayView.kt
=> app: replace reduce with reduceOrNull

stustapay/core/service/customer/customer.py, stustapay/tests/test_customer_service.py
- removed bic generation in sepa export
- removed export country code test as all ibans in db have already been checked
- added more description to export errors
=> Removed BIC in SEPA export

stustapay/core/service/customer/customer.py
Removed bic as it is not the problem of the transaction
=> cp export: removed bic again

pyproject.toml, stustapay/administration/routers/till_registers.py, stustapay/administration/routers/user.py, stustapay/bon/pdflatex.py, stustapay/core/healthcheck.py, stustapay/core/populate.py, stustapay/core/schema/account.py, stustapay/core/schema/cashier.py, stustapay/core/schema/customer.py, stustapay/core/schema/order.py, stustapay/core/schema/user.py, stustapay/core/service/customer/sumup.py, stustapay/core/service/order/booking.py, stustapay/core/service/order/order.py, stustapay/core/service/order/stats.py, stustapay/core/util.py, stustapay/customer_portal/routers/sumup.py, stustapay/terminalserver/router/base.py, stustapay/terminalserver/router/cashier.py, stustapay/terminalserver/router/customer.py, stustapay/terminalserver/router/user.py
- explicit pydantic 2.0 deps
- fix pydantic property usages
=> Fix pydantic bump

pyproject.toml, stustapay/framework/database.py, website/docs/developer-documentation/simulator.md
- Added docu which describes how to view the web interfaces for
developers
- Fixed bcrypt dependency as it breaks otherwise
- Added port config such that docker deployment works
=> Docu for viewing web interfaces for developer

stustapay/token_generation.py
=> misc: new nfc token generation

Makefile, stustapay/festivalsimulator/festivalsimulator.py
- festival simulator randomly registers payouts with and without donations
- fixed makefile to only lint python folders. This avoids linting of python venvs.
=> feat(simulator): added payout registration to simulator

stustapay/tse/tse_switchover.py
patch tse_switchover utility for new database names in tse table
=> fix db renames in tse_switchover util

api/administration.json, stustapay/administration/routers/tree.py, stustapay/ticket_shop/pretix.py, web/apps/administration/src/api/generated/api.ts, web/apps/administration/src/app/routes/nodes/event-settings/TabPretix.tsx, web/apps/administration/src/locales/en/translations.ts
=> feat(admin): fetch list of pretix products for easy ticket coupling

api/administration.json, stustapay/administration/routers/customer.py, stustapay/core/service/account.py, web/apps/administration/src/api/generated/api.ts, web/apps/administration/src/app/Router.tsx, web/apps/administration/src/app/routes/customers/CustomerOverview.tsx, web/apps/administration/src/app/routes/customers/CustomerPageLayout.tsx, web/apps/administration/src/app/routes/customers/CustomersWithBlockedPayout.tsx, web/apps/administration/src/app/routes/customers/index.ts, web/apps/administration/src/locales/en/translations.ts
=> feat(admin): add list for customers with blocked payouts

stustapay/core/schema/account.py, stustapay/core/schema/db_code/0004-functions.sql, stustapay/core/service/order/order.py, stustapay/core/service/till/register.py
=> fix(core): make bookings tolerant to near zero balances

web/apps/customerportal/src/app/routes/OrderList.tsx
=> fix(cp): order list with green minus zero

stustapay/core/service/customer/customer.py, web/apps/customerportal/src/app/routes/PayoutInfo.tsx
=> fix(cp): ignore white spaces in iban entry

stustapay/core/schema/mail.py, stustapay/core/service/mail.py, web/apps/customerportal/src/locales/en/translations.ts
fixed multiple mail send by moving mail retrieval into mail send db transaction
fixes issue #593
=> fix(mail): send mail only once

stustapay/reports/render.py
fancy raw json data as attachment in pdf report
=> add raw json data to reports
